version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    ports:
    - 127.0.0.1:8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/keycloak/MyRealm-realm.json
    volumes:
      - ./keycloak/MyRealm-realm.json:/tmp/keycloak/MyRealm-realm.json:ro