server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/MyRealm
          jwk-set-uri: http://localhost:8080/auth/realms/MyRealm/protocol/openid-connect/certs